### ISSUE TITLE
Should "Splitting reactions with 10 or more compounds" become the default behavior

### ISSUE THREAD

**Issue by spikeliu** [zhanglab/psamm-import#17]
psamm-import now would turn reactions into list representation in Yaml files if they have more than 10 compounds.
- Maybe put those very long reactions into separate files.
- Put a tag(option flag) this function.

**Comment by jonls** [comment]
How would creating separate files interact with #14 splitting by subsystem?

**Comment by spikeliu** [comment]
No, I have another issue for that, this is just for split reactions, not for split subsystems.
She mentioned that if in most cases, the biomass reaction would get really long, maybe to put them into a separate file.

**Comment by jonls** [comment]
Yes, I'm asking how this would work if the user also wants to split by subsystem. Would large reactions only go into a separate file if the user specified to not split by subsystem? Or the opposite? What I'm asking is, is it possible to have both #14 and this reaction splitting at the same time working in a reasonable way?

**Comment by spikeliu** [comment]
She said the content after the first dot above could be optional, but the second one is a kind of must done, which means we may need to provide a option flag to decide whether to transform the reaction into list representation.

**Comment by spikeliu** [comment]
I think this is just related to pull request #12

**Comment by jonls** [comment]
Ok, let's focus on the second part first then.
