### ISSUE TITLE
psamm-import-bigg (cobrajson) should import irreversible as such

### ISSUE THREAD

**Issue by jonls** [zhanglab/psamm-import#18]
Currently, a reaction with a lower flux bound of zero seems to be imported as a reversible reaction with a limit in `limits.yaml` of zero. This can be confusing because the reaction seems to be reversible when looking at the reaction definition in `reactions.yaml` but in reality it is not. There could be some cases where a reaction should ideally be imported with a limit instead of changing the reversibility but this would probably be a rare case that the user should be able to sort out.

**Comment by jonls** [comment]
In the `cobrajson` parser, when we observe a reaction with a lower flux bound of zero, that reaction should be converted to a forward-only reaction. Similarly, we can convert reactions with an upper flux bound of zero to a reverse-only reaction.

**Comment by dozingpip** [comment]
https://github.com/zhanglab/psamm-import/pull/23
