### ISSUE TITLE
Biomass reaction not written in model.yaml

### ISSUE THREAD

**Issue by pbaCamille** [zhanglab/psamm-import#48]
There is an issue regarding import of sbml files. This is the message displayed to my screen, even if the Biomass reaction is detected, the model.yaml file doen't include the information anymore.

INFO: Detected biomass reaction: R_BIOMASS__45__REACTION
INFO: Removing compound prefix 'M_'
INFO: Removing reaction prefix 'R_'
Model: SBML
- Biomass reaction: None
- Compartments: 3
- Compounds: 12792
- Reactions: 14782
- Genes: 1048
INFO: e is extracellular compartment
INFO: Using default flux limit of 99999.0

**Comment by jonls** [comment]
@pbaCamille Thanks for reporting this issue. The problem should be fixed now, when you reinstall or upgrade psamm-import. Please let us know if you have additional issues.
